{{
    config(
        materialized = 'table',
        transient = true
    )
}}

SELECT
    CAST(p.PROJECT_ID AS NUMBER)                AS PROJECT_ID,
    TRIM(p.PROJECT_NAME)                        AS PROJECT_NAME,
    CAST(p.COMPANY_ID AS NUMBER)                AS COMPANY_ID,
    CAST(p.OWNING_DEPARTMENT_ID AS NUMBER)      AS OWNING_DEPARTMENT_ID,
    TRIM(p.PROJECT_TYPE)                        AS PROJECT_TYPE,
    TRIM(p.PROJECT_BILLING_TYPE)                AS PROJECT_BILLING_TYPE,
    TRY_CAST(p.PROJECT_BUDGET_USD AS NUMBER(18,2)) AS PROJECT_BUDGET_USD,
    TRIM(p.PROJECT_STATUS)                      AS PROJECT_STATUS,
    TRY_TO_DATE(p.START_DATE)                  AS START_DATE,
    TRY_TO_DATE(p.PLANNED_END_DATE)            AS PLANNED_END_DATE,
    TRY_TO_DATE(p.ACTUAL_END_DATE)             AS ACTUAL_END_DATE,
    TRY_TO_DATE(p.ADDED_DATE)                 AS ADDED_DATE,
    TRY_TO_DATE(p.UPDATED_DATE)               AS UPDATED_DATE,
    CAST(p.IS_ACTIVE AS BOOLEAN)                AS IS_ACTIVE,
    CASE
        WHEN TRIM(p.PROJECT_STATUS) = 'Completed' AND TRY_TO_DATE(p.ACTUAL_END_DATE) IS NOT NULL THEN 'Completed'
        WHEN TRIM(p.PROJECT_STATUS) = 'Active' AND TRY_TO_DATE(p.PLANNED_END_DATE) < CURRENT_DATE() THEN 'Overdue'
        WHEN TRIM(p.PROJECT_STATUS) = 'Active' THEN 'Active'
        WHEN TRIM(p.PROJECT_STATUS) = 'Planning' THEN 'Planning'
        ELSE TRIM(p.PROJECT_STATUS)
    END AS PROJECT_LIFECYCLE_STATE,
    CASE
        WHEN TRY_TO_DATE(p.START_DATE) > TRY_TO_DATE(p.PLANNED_END_DATE) THEN FALSE
        WHEN TRY_TO_DATE(p.ACTUAL_END_DATE) < TRY_TO_DATE(p.START_DATE) THEN FALSE
        WHEN TRIM(p.PROJECT_STATUS) = 'Completed' AND TRY_TO_DATE(p.ACTUAL_END_DATE) IS NULL THEN FALSE
        ELSE TRUE
    END AS IS_DATE_SEQUENCE_VALID,
    REGEXP_SUBSTR(p.__STG_FILE_NAME, 'day_(\\d+)', 1, 1, 'e') AS __SRC_DELTA_DAY

FROM {{ source('bronze', 'PROJECTS') }} p
WHERE p.PROJECT_ID IS NOT NULL
  AND TRIM(p.PROJECT_NAME) != ''
  AND CAST(p.COMPANY_ID AS NUMBER) IN (SELECT COMPANY_ID FROM {{ ref('silver_companies') }})
  AND CAST(p.OWNING_DEPARTMENT_ID AS NUMBER) IN (SELECT DEPARTMENT_ID FROM {{ ref('silver_departments') }})
