{{
    config(
        materialized = 'table',
        transient = true
    )
}}

SELECT
    CAST(pt.PROJECT_TECHNOLOGY_ID AS NUMBER)  AS PROJECT_TECHNOLOGY_ID,
    CAST(pt.PROJECT_ID AS NUMBER)             AS PROJECT_ID,
    CAST(pt.SKILL_ID AS NUMBER)               AS SKILL_ID,
    TRIM(pt.REQUIRED_PROFICIENCY_LEVEL)       AS REQUIRED_PROFICIENCY_LEVEL,
    CAST(pt.IS_PRIMARY_TECHNOLOGY AS BOOLEAN) AS IS_PRIMARY_TECHNOLOGY,
    CASE UPPER(TRIM(pt.REQUIRED_PROFICIENCY_LEVEL))
        WHEN 'BEGINNER'     THEN 1
        WHEN 'INTERMEDIATE' THEN 2
        WHEN 'ADVANCED'     THEN 3
        WHEN 'EXPERT'       THEN 4
    END AS REQUIRED_PROFICIENCY_RANK,
    REGEXP_SUBSTR(pt.__STG_FILE_NAME, 'day_(\\d+)', 1, 1, 'e') AS __SRC_DELTA_DAY

FROM {{ source('bronze', 'PROJECT_TECHNOLOGIES') }} pt
WHERE pt.PROJECT_TECHNOLOGY_ID IS NOT NULL
  AND CAST(pt.PROJECT_ID AS NUMBER) IN (SELECT PROJECT_ID FROM {{ ref('silver_projects') }})
  AND CAST(pt.SKILL_ID AS NUMBER) IN (SELECT SKILL_ID FROM {{ ref('silver_skills') }})
