{{
    config(
        materialized = 'table',
        transient = true
    )
}}

SELECT
    CAST(a.ASSIGNMENT_ID AS NUMBER)         AS ASSIGNMENT_ID,
    CAST(a.EMPLOYEE_ID AS NUMBER)           AS EMPLOYEE_ID,
    CAST(a.PROJECT_ID AS NUMBER)            AS PROJECT_ID,
    TRIM(a.ASSIGNMENT_ROLE)                 AS ASSIGNMENT_ROLE,
    CAST(a.ALLOCATION_PERCENT AS NUMBER)    AS ALLOCATION_PERCENT,
    TRY_TO_DATE(a.ASSIGNMENT_START_DATE)   AS ASSIGNMENT_START_DATE,
    TRY_TO_DATE(a.ASSIGNMENT_END_DATE)     AS ASSIGNMENT_END_DATE,
    CAST(a.ALLOCATION_PERCENT AS NUMBER) / 100.0 AS ALLOCATION_FRACTION,
    CASE
        WHEN TRY_TO_DATE(a.ASSIGNMENT_END_DATE) IS NULL
             OR TRY_TO_DATE(a.ASSIGNMENT_END_DATE) >= CURRENT_DATE()
        THEN TRUE ELSE FALSE
    END AS IS_ACTIVE_ASSIGNMENT,
    CAST(a.ALLOCATION_PERCENT AS NUMBER) BETWEEN 0 AND 100 AS IS_ALLOCATION_VALID,
    REGEXP_SUBSTR(a.__STG_FILE_NAME, 'day_(\\d+)', 1, 1, 'e') AS __SRC_DELTA_DAY

FROM {{ source('bronze', 'EMPLOYEE_PROJECT_ASSIGNMENTS') }} a
WHERE a.ASSIGNMENT_ID IS NOT NULL
  AND TRIM(a.EMPLOYEE_ID) != ''
  AND TRIM(a.PROJECT_ID) != ''
  AND CAST(a.EMPLOYEE_ID AS NUMBER) IN (SELECT EMPLOYEE_ID FROM {{ ref('silver_employees') }})
  AND CAST(a.PROJECT_ID AS NUMBER) IN (SELECT PROJECT_ID FROM {{ ref('silver_projects') }})
  AND CAST(a.ALLOCATION_PERCENT AS NUMBER) BETWEEN 0 AND 100
