{{
    config(
        materialized = 'table',
        transient = true
    )
}}

SELECT
    CAST(da.ACCESS_EVENT_ID AS NUMBER)       AS ACCESS_EVENT_ID,
    TRIM(da.ACCESS_ID)                       AS ACCESS_ID,
    CAST(da.OFFICE_ID AS NUMBER)             AS OFFICE_ID,
    TRY_TO_DATE(da.ACCESS_DATE)             AS ACCESS_DATE,
    TRY_TO_TIMESTAMP_NTZ(da.ACCESS_TIMESTAMP) AS ACCESS_TIMESTAMP,
    UPPER(TRIM(da.ACCESS_EVENT_TYPE))        AS ACCESS_EVENT_TYPE,
    TRY_TO_DATE(da.ACCESS_DATE)             AS ACCESS_DATE_STANDARDIZED,
    TRY_TO_TIME(da.ACCESS_TIMESTAMP)        AS ACCESS_TIME,
    EXTRACT(HOUR FROM TRY_TO_TIMESTAMP_NTZ(da.ACCESS_TIMESTAMP)) AS ACCESS_HOUR,
    UPPER(TRIM(da.ACCESS_EVENT_TYPE))        AS ACCESS_EVENT_TYPE_STANDARDIZED,
    CASE
        WHEN TRY_TO_DATE(da.ACCESS_DATE) = TRY_TO_DATE(da.ACCESS_TIMESTAMP)
        THEN TRUE ELSE FALSE
    END AS IS_DATE_CONSISTENT,
    REGEXP_SUBSTR(da.__STG_FILE_NAME, 'day_(\\d+)', 1, 1, 'e') AS __SRC_DELTA_DAY

FROM {{ source('bronze', 'EMPLOYEE_DAILY_ACCESS') }} da
WHERE da.ACCESS_EVENT_ID IS NOT NULL
  AND TRIM(da.ACCESS_ID) != ''
  AND UPPER(TRIM(da.ACCESS_EVENT_TYPE)) IN ('IN', 'OUT')
  AND TRY_TO_DATE(da.ACCESS_DATE) IS NOT NULL
  AND TRY_TO_TIMESTAMP_NTZ(da.ACCESS_TIMESTAMP) IS NOT NULL
  AND CAST(da.OFFICE_ID AS NUMBER) IN (SELECT OFFICE_ID FROM {{ ref('silver_offices') }})
